# Generated by Django 5.2.1 on 2025-12-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressupdate',
            name='image',
        ),
    ]
