# Generated by Django 5.2.1 on 2025-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price_cents',
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
