# Generated by Django 5.2.1 on 2025-06-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_plan_price_cents_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
